### PR TITLE
Sym storage not working

### LINKED ISSUE #15: FEM driver with symmetric matrix storage not working
Hi @victorsndvg,

I have realized that the Pardiso solvers are not working properly for symmetric matrices. 

I have used a symmetric matrix in the femdriver, and the tests do not pass. See here:

https://github.com/gridap/GridapPardiso.jl/blob/sym_storage_not_working/test/femdriver.jl

Can you try to fix it?

Thanks!

### PR DESCRIPTION
**Pull request by victorsndvg**
fix #15

### CODE REVIEW

File: src/LinearSolver.jl [hunk 1]
```diff
@@ -83,23 +83,32 @@ PardisoSolver() = PardisoSolver(MTYPE_REAL_NON_SYMMETRIC,
...
+PardisoSolver(mtype::Int) = 
     PardisoSolver(mtype, new_iparm(), MSGLVL_QUIET, new_pardiso_handle())
 
+PardisoSolver(::Type{<:AbstractSparseMatrix{Tv,Ti}}) where {Tv,Ti}= 
+    PardisoSolver(GridapPardiso.MTYPE_REAL_NON_SYMMETRIC)
+
+PardisoSolver(::Type{SymSparseMatrixCSR{Bi,Tv,Ti}}) where {Bi,Tv,Ti}= 
+    PardisoSolver(GridapPardiso.MTYPE_REAL_SYMMETRIC_INDEFINITE)
+
+PardisoSolver(op::AffineFEOperator) =
```
Comment (fverdugo) [inline src/LinearSolver.jl]: Instead of implementing it only for `AffineFEOperator`, I would do it for any `FEOperator` like this:

```julia
PardisoSolver(op::FEOperator) = PardisoSolver(get_matrix_type(op))
```

And then, implement 

```julia
function get_matrix_type(op::FEOperator)
  @abstractmethod
end

function get_matrix_type(op::AffineFEOperator)
  typeof(get_matrix(op))
end
```

These two last functions will be eventually moved to the Gridap repo.

**Review by fverdugo — CHANGES_REQUESTED** [review]

**Comment by fverdugo** [comment]
hi @victorsndvg

I have some comments to the PR. Minor things. I can merge the PR once they are fixed.

File: src/LinearSolver.jl (hunk 1 above)
Comment (victorsndvg) [reply src/LinearSolver.jl]: Commit d88a2a0 solves this comment

**Review by fverdugo — APPROVED** [review]
